import {
    Activity,
    Apple,
    ArrowDownWideNarrow,
    ArrowLeft,
    ArrowRight,
    Armchair,
    AtSign,
    BadgeCheck,
    Ban,
    Bell,
    Bot,
    Castle,
    Club,
    Coffee,
    Crown,
    Diamond,
    Check,
    ChevronDown,
    ChevronRight,
    CircleCheck,
    CircleUser,
    CircleX,
    Clock,
    Coins,
    Compass,
    Copy,
    Dices,
    Ellipsis,
    Expand,
    FaceSlightlySmiling,
    FaceSlightlySmilingPlus,
    Flag,
    Flame,
    Gamepad2,
    Hand,
    Hash,
    Heart,
    History,
    House,
    Info,
    KeyRound,
    Leaf,
    Lightbulb,
    Link2,
    Lock,
    Maximize2,
    LogOut,
    Medal,
    MoonStar,
    Menu,
    Mic,
    MicOff,
    Eye,
    Headphones,
    HeadphoneOff,
    Minimize2,
    MessageCircle,
    MessageCircleOff,
    PanelLeftClose,
    PanelLeftOpen,
    PanelRightClose,
    PanelRightOpen,
    Palette,
    Pencil,
    PhoneOff,
    Play,
    Plus,
    RefreshCw,
    Reply,
    Search,
    Send,
    Settings,
    Share2,
    Shrink,
    Shield,
    Signal,
    Smartphone,
    Spade,
    Sparkles,
    Sprout,
    Star,
    Swords,
    Target,
    Timer,
    Trash,
    Trophy,
    TriangleAlert,
    Undo2,
    UserCheck,
    UserPlus,
    Users,
    Volume2,
    VolumeX,
    Wallet,
    WifiOff,
    X,
    Zap,
    type IconNode
} from 'lucide';

import { registerIcons } from './registry.ts';

export const ALL_ICONS = {
    'activity': Activity,
    'add': Plus,
    'alert': TriangleAlert,
    'at': AtSign,
    'back': ArrowLeft,
    'bell': Bell,
    'block': Ban,
    'bot': Bot,
    'crest-castle': Castle,
    'crest-crown': Crown,
    'crest-cup': Coffee,
    'crest-moon': MoonStar,
    'crest-sprout': Sprout,
    'cards': Spade,
    'suit-clubs': Club,
    'suit-diamonds': Diamond,
    'suit-hearts': Heart,
    'suit-spades': Spade,
    'chats': MessageCircle,
    'chat-off': MessageCircleOff,
    'check-circle': CircleCheck,
    'chevron-down': ChevronDown,
    'chevron-right': ChevronRight,
    'clock': Clock,
    'close': X,
    'compact': Minimize2,
    'coins': Coins,
    'copy': Copy,
    'dice': Dices,
    'discover': Compass,
    'edit': Pencil,
    'error-circle': CircleX,
    'expand': Maximize2,
    'flame': Flame,
    'forward': ArrowRight,
    'friend-add': UserPlus,
    'friend-check': UserCheck,
    'games': Gamepad2,
    'history': History,
    'home': House,
    'info': Info,
    'invite': Link2,
    'key': KeyRound,
    'lock': Lock,
    'me': CircleUser,
    'medal': Medal,
    'menu': Menu,
    'more': Ellipsis,
    'panel-close': PanelRightClose,
    'panel-open': PanelRightOpen,
    'people': Users,
    'play': Play,
    'phone': Smartphone,
    'refresh': RefreshCw,
    'report': Flag,
    'search': Search,
    'seat': Armchair,
    'selected': Check,
    'send': Send,
    'settings': Settings,
    'share': Share2,
    'sidebar-close': PanelLeftClose,
    'sidebar-open': PanelLeftOpen,
    'shield': Shield,
    'sign-out': LogOut,
    'signal': Signal,
    'fullscreen': Expand,
    'fullscreen-exit': Shrink,
    'sound': Volume2,
    'sound-off': VolumeX,
    'sort': ArrowDownWideNarrow,
    'sparkles': Sparkles,
    'star': Star,
    'target': Target,
    'timer': Timer,
    'trophy': Trophy,
    'verified': BadgeCheck,
    'versus': Swords,
    'voice': Mic,
    'wallet': Wallet,
    'wifi-off': WifiOff,
    'zap': Zap,
    'smile': FaceSlightlySmiling,
    'react': FaceSlightlySmilingPlus,
    'hand': Hand,
    'heart': Heart,
    'leaf': Leaf,
    'food': Apple,
    'idea': Lightbulb,
    'hash': Hash,
    'flag': Flag,
    'reply': Reply,
    'trash': Trash,
    'palette': Palette,
    'voice-off': MicOff,
    'hang-up': PhoneOff,
    'listen': Headphones,
    'deafen': HeadphoneOff,
    'watch': Eye,
    'undo': Undo2
} satisfies Record<string, IconNode>;

export type IconName = keyof typeof ALL_ICONS;

registerIcons(ALL_ICONS);
