import {
    Activity,
    ArrowLeft,
    ArrowRight,
    Armchair,
    AtSign,
    BadgeCheck,
    Ban,
    Bell,
    Bot,
    Check,
    ChevronDown,
    ChevronRight,
    CircleCheck,
    CircleUser,
    CircleX,
    Clock,
    Coins,
    Compass,
    Copy,
    Dices,
    Ellipsis,
    Eye,
    EyeOff,
    Flag,
    Flame,
    Gamepad2,
    Gift,
    History,
    House,
    Info,
    KeyRound,
    Languages,
    Link2,
    Lock,
    LogOut,
    Medal,
    Menu,
    MessageCircle,
    Mic,
    MicOff,
    Moon,
    Palette,
    PanelRightClose,
    PanelRightOpen,
    PartyPopper,
    Pencil,
    Plus,
    RefreshCw,
    Search,
    Send,
    Settings,
    Share2,
    Shield,
    ShieldAlert,
    Signal,
    Smartphone,
    Spade,
    Sparkles,
    Star,
    Sun,
    Swords,
    Target,
    Timer,
    Trophy,
    TriangleAlert,
    UserCheck,
    UserMinus,
    UserPlus,
    Users,
    UserX,
    Volume2,
    VolumeX,
    WifiOff,
    X,
    Zap,
    type IconNode
} from 'lucide';

export const ICONS = {
    'activity': Activity,
    'add': Plus,
    'alert': TriangleAlert,
    'at': AtSign,
    'back': ArrowLeft,
    'bell': Bell,
    'block': Ban,
    'bot': Bot,
    'cards': Spade,
    'celebrate': PartyPopper,
    'chats': MessageCircle,
    'check-circle': CircleCheck,
    'chevron-down': ChevronDown,
    'chevron-right': ChevronRight,
    'clock': Clock,
    'close': X,
    'coins': Coins,
    'copy': Copy,
    'dice': Dices,
    'discover': Compass,
    'edit': Pencil,
    'error-circle': CircleX,
    'eye': Eye,
    'eye-off': EyeOff,
    'flame': Flame,
    'forward': ArrowRight,
    'friend-add': UserPlus,
    'friend-check': UserCheck,
    'friend-remove': UserMinus,
    'friend-x': UserX,
    'games': Gamepad2,
    'gift': Gift,
    'history': History,
    'home': House,
    'info': Info,
    'invite': Link2,
    'key': KeyRound,
    'language': Languages,
    'lock': Lock,
    'me': CircleUser,
    'medal': Medal,
    'menu': Menu,
    'mic': Mic,
    'mic-off': MicOff,
    'more': Ellipsis,
    'palette': Palette,
    'panel-close': PanelRightClose,
    'panel-open': PanelRightOpen,
    'people': Users,
    'phone': Smartphone,
    'refresh': RefreshCw,
    'report': Flag,
    'search': Search,
    'seat': Armchair,
    'selected': Check,
    'send': Send,
    'settings': Settings,
    'share': Share2,
    'shield': Shield,
    'shield-alert': ShieldAlert,
    'sign-out': LogOut,
    'signal': Signal,
    'sound': Volume2,
    'sound-off': VolumeX,
    'sparkles': Sparkles,
    'star': Star,
    'target': Target,
    'theme-dawn': Sun,
    'theme-dusk': Moon,
    'timer': Timer,
    'trophy': Trophy,
    'verified': BadgeCheck,
    'versus': Swords,
    'voice': Mic,
    'wifi-off': WifiOff,
    'zap': Zap
} satisfies Record<string, IconNode>;

export type IconName = keyof typeof ICONS;
